In [3]:
from planner.utils.traj_saver import ExperimentTrajectoryManager
import os
import pandas as pd

In [11]:

trajectory_folders = ["scene1_trajs", "scene2_trajs", "scene3_trajs"]
repo_path = os.getcwd()

raw_dict = {"scene":[], "sample":[], "traj_len":[], "me_cost":[], "safety_cost":[]}


exp_traj_manager = ExperimentTrajectoryManager()
for folder in trajectory_folders:
    traj_folder = os.path.join(repo_path, "collected_trajs", folder)
    traj_files = [os.path.join(traj_folder, f) for f in os.listdir(os.path.join(traj_folder))]
    traj_files.sort()
    for file in traj_files:
        fname = os.path.splitext(os.path.basename(file))[0]
        sample_no = fname.split("_")[-1]
        print(fname, sample_no)
        exp_traj_manager.load_from_file(file)

        for scene, scene_dict in exp_traj_manager.trajectories.items():

            traj_len = 0    
            me_cost = 0
            safety_cost = 0
            for phase, phase_dict in scene_dict.items():
                traj_len += len(phase_dict["trajectory"]) -1
                me_cost += phase_dict["me_cost"][1:].sum()
                safety_cost += phase_dict["safety_cost"][1:].sum()
            
            print(f"traj_len {traj_len} me_cost {me_cost} safety_cost {safety_cost}")
            raw_dict["scene"].append(scene)
            raw_dict["sample"].append(sample_no)
            raw_dict["traj_len"].append(traj_len)
            raw_dict["me_cost"].append(me_cost)
            raw_dict["safety_cost"].append(safety_cost)

        print("------------")

scene_RRTConnect_baseline baseline
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_baseline.pkl
traj_len 2 me_cost 0.5275718401578618 safety_cost 0.05957088671682956
------------
scene_RRTConnect_sample_0 0
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_0.pkl
traj_len 4 me_cost 0.7493662784186976 safety_cost 0.13231109476689673
------------
scene_RRTConnect_sample_1 1
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_1.pkl
traj_len 4 me_cost 0.6006643763064365 safety_cost 0.36216962083917453
------------
scene_RRTConnect_sample_2 2
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_2.pkl
traj_len 4 me_cost 0.576708399203744 safety_cost 0.304928003318533
------------
scene_RRTConnect_sample_3 3
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_3.pkl
traj_len 4 me_cost 0.9896173443938985 safety_cost 0.2014988785971821
------------
scene_RRTConnect_sample_4 4
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_4.pkl
traj_len 4 me_cost 0.9524557434699044 safety_cost 0.22264987489365445
------------
scene_RRTConnect_sample_5 5
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_5.pkl
traj_len 4 me_cost 0.6904797107522475 safety_cost 0.18903027497218355
------------
scene_RRTConnect_sample_6 6
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_6.pkl
traj_len 4 me_cost 0.6980194442916533 safety_cost 0.11510391668328651
------------
scene_RRTConnect_sample_7 7
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_7.pkl
traj_len 4 me_cost 0.7860596643269153 safety_cost 0.37302495690654014
------------
scene_RRTConnect_sample_8 8
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_8.pkl
traj_len 4 me_cost 1.0372622247931895 safety_cost 0.3012229711019835
------------
scene_RRTConnect_sample_9 9
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene1_trajs/scene_RRTConnect_sample_9.pkl
traj_len 4 me_cost 0.6849827327051649 safety_cost 0.35541912547685917
------------
scene_level2_RRTConnect_baseline baseline
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_baseline.pkl
traj_len 2 me_cost 1.1785978199832445 safety_cost 0.08149909545814829
------------
scene_level2_RRTConnect_sample_0 0
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_0.pkl
traj_len 4 me_cost 1.5667998520612003 safety_cost 0.3466916910354644
------------
scene_level2_RRTConnect_sample_1 1
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_1.pkl
traj_len 4 me_cost 1.2796780402322625 safety_cost 0.42984355639834204
------------
scene_level2_RRTConnect_sample_2 2
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_2.pkl
traj_len 4 me_cost 1.2796816979339412 safety_cost 0.5305485431713538
------------
scene_level2_RRTConnect_sample_4 4
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_4.pkl
traj_len 4 me_cost 1.8166656032097452 safety_cost 0.1748500289219903
------------
scene_level2_RRTConnect_sample_5 5
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_5.pkl
traj_len 4 me_cost 1.3059528516347603 safety_cost 0.48451318121659026
------------
scene_level2_RRTConnect_sample_6 6
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_6.pkl
traj_len 4 me_cost 1.2918454070998568 safety_cost 0.2016365054119284
------------
scene_level2_RRTConnect_sample_7 7
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_7.pkl
traj_len 4 me_cost 1.9578102180916872 safety_cost 0.23642248371089009
------------
scene_level2_RRTConnect_sample_9 9
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene2_trajs/scene_level2_RRTConnect_sample_9.pkl
traj_len 4 me_cost 1.6258609390020342 safety_cost 0.43205472988328036
------------
scene_level3_RRTConnect_baseline baseline
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_baseline.pkl
traj_len 22 me_cost 0.7781629823384759 safety_cost 1.1477206089690637
------------
scene_level3_RRTConnect_sample_0 0
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_0.pkl
traj_len 4 me_cost 0.9707721934923514 safety_cost 0.16369168002788997
------------
scene_level3_RRTConnect_sample_1 1
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_1.pkl
traj_len 4 me_cost 0.9236142070791183 safety_cost 0.38451424842588156
------------
scene_level3_RRTConnect_sample_2 2
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_2.pkl
traj_len 25 me_cost 1.8282725439628555 safety_cost 0.35415095034033495
------------
scene_level3_RRTConnect_sample_3 3
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_3.pkl
traj_len 4 me_cost 2.358130277195717 safety_cost 0.47556736619756396
------------
scene_level3_RRTConnect_sample_4 4
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_4.pkl
traj_len 7 me_cost 2.0071534943680795 safety_cost 0.5254582981495274
------------
scene_level3_RRTConnect_sample_5 5
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_5.pkl
traj_len 18 me_cost 1.8261246671903333 safety_cost 0.2103138569509395
------------
scene_level3_RRTConnect_sample_6 6
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_6.pkl
traj_len 4 me_cost 1.9146687868092789 safety_cost 0.10723097576964331
------------
scene_level3_RRTConnect_sample_7 7
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_7.pkl
traj_len 30 me_cost 2.1781444669307812 safety_cost 0.4306656340028262
------------
scene_level3_RRTConnect_sample_8 8
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_8.pkl
traj_len 4 me_cost 2.142168651904371 safety_cost 0.2916217786295028
------------
scene_level3_RRTConnect_sample_9 9
Loaded trajectories from /mnt/saad/FailBench/collected_trajs/scene3_trajs/scene_level3_RRTConnect_sample_9.pkl
traj_len 8 me_cost 1.530184663235732 safety_cost 0.8045631119830781
------------

In [19]:
exp_traj_manager.report()

Stored Experiment Trajectories:
Total scenarios: 1
Total phases: 2
- scene_level3: ['phase6', 'phase7']

Detailed Trajectories:

Scenario: scene_level3
  Phase: phase6
    Length of traj: 7.
    trajectory (<class 'list'>): [array([ 1.13196565e+00,  5.22655488e-01, -2.49730935e+00, -2.12980781e+00,
        3.06306233e-01,  1.67321584e+00, -6.86352974e-01,  1.97678742e-04,
        1.94396046e-04]), array([ 1.13371938e+00,  5.19392259e-01, -2.49747693e+00, -2.12952512e+00,
        3.03135635e-01,  1.67382202e+00, -6.87217263e-01,  2.21306450e-04,
        2.02827060e-04]), array([ 9.96543337e-01,  3.46078683e-01, -2.63682799e+00, -2.14370953e+00,
        1.71219953e-01,  1.83475131e+00, -9.24121085e-01,  1.98778335e-04,
        1.94788410e-04]), array([ 9.94869453e-01,  3.43963833e-01, -2.63852842e+00, -2.14388262e+00,
        1.69610259e-01,  1.83671504e+00, -9.27011892e-01,  1.98503436e-04,
        1.94690319e-04]), array([ 9.93195569e-01,  3.41848983e-01, -2.64022884e+00, -2.14405570e+00,
        1.68000565e-01,  1.83867878e+00, -9.29902699e-01,  1.98228538e-04,
        1.94592228e-04]), array([ 9.91521686e-01,  3.39734133e-01, -2.64192927e+00, -2.14422878e+00,
        1.66390870e-01,  1.84064251e+00, -9.32793506e-01,  1.97953640e-04,
        1.94494137e-04]), array([ 9.89847802e-01,  3.37619283e-01, -2.64362969e+00, -2.14440187e+00,
        1.64781176e-01,  1.84260624e+00, -9.35684313e-01,  1.97678742e-04,
        1.94396046e-04])].
    goal_pos (<class 'numpy.ndarray'>): [-0.00582112 -0.47168895  0.425     ].
    me_cost (<class 'numpy.ndarray'>): [0.         0.005      0.40975381 0.005      0.005      0.005
 0.005     ].
    safety_cost (<class 'numpy.ndarray'>): [0.02231755 0.02232418 0.13246993 0.13165423 0.13063551 0.12942306
 0.12848277].
  Phase: phase7
    Length of traj: 3.
    trajectory (<class 'list'>): [array([ 9.89911146e-01,  3.34313574e-01, -2.64219162e+00, -2.15084092e+00,
        1.64527220e-01,  1.84137495e+00, -9.35556256e-01,  7.10809095e-08,
        5.33216696e-08]), array([ 9.92120246e-01,  3.31172616e-01, -2.64206331e+00, -2.15048882e+00,
        1.61387138e-01,  1.84167316e+00, -9.35961227e-01,  2.61577407e-05,
        9.62699775e-06]), array([ 7.22172427e-01, -1.15654591e-01, -2.89725676e+00, -2.46373757e+00,
       -5.14203062e-02,  2.57542665e+00, -1.34776629e+00,  7.10809095e-08,
        5.33216696e-08])].
    goal_pos (<class 'numpy.ndarray'>): [-0.27184191 -0.39795684  0.14989224].
    me_cost (<class 'numpy.ndarray'>): [0.         0.005      1.09043085].
    safety_cost (<class 'numpy.ndarray'>): [0.1304942  0.12957343 0.        ].

In [16]:
df = pd.DataFrame(raw_dict)
df["total_cost"] = df["me_cost"] + df["safety_cost"]

df["avg_me_cost"] = df["me_cost"] / df["traj_len"]
df["avg_safety_cost"] = df["safety_cost"] / df["traj_len"]
df["avg_total_cost"] = df["total_cost"] / df["traj_len"]

df.sort_values(by=["scene", "total_cost"], ascending=[True, True], inplace=True)
df

,scene,sample,traj_len,me_cost,safety_cost,total_cost,avg_me_cost,avg_safety_cost,avg_total_cost
0,scene,baseline,2,0.527572,0.059571,0.587143,0.263786,0.029785,0.293571
7,scene,6,4,0.698019,0.115104,0.813123,0.174505,0.028776,0.203281
6,scene,5,4,0.690480,0.189030,0.879510,0.172620,0.047258,0.219877
3,scene,2,4,0.576708,0.304928,0.881636,0.144177,0.076232,0.220409
1,scene,0,4,0.749366,0.132311,0.881677,0.187342,0.033078,0.220419
2,scene,1,4,0.600664,0.362170,0.962834,0.150166,0.090542,0.240708
10,scene,9,4,0.684983,0.355419,1.040402,0.171246,0.088855,0.260100
8,scene,7,4,0.786060,0.373025,1.159085,0.196515,0.093256,0.289771
5,scene,4,4,0.952456,0.222650,1.175106,0.238114,0.055662,0.293776
4,scene,3,4,0.989617,0.201499,1.191116,0.247404,0.050375,0.297779
9,scene,8,4,1.037262,0.301223,1.338485,0.259316,0.075306,0.334621
11,scene_level2,baseline,2,1.178598,0.081499,1.260097,0.589299,0.040750,0.630048
17,scene_level2,6,4,1.291845,0.201637,1.493482,0.322961,0.050409,0.373370
13,scene_level2,1,4,1.279678,0.429844,1.709522,0.319920,0.107461,0.427380
16,scene_level2,5,4,1.305953,0.484513,1.790466,0.326488,0.121128,0.447617
14,scene_level2,2,4,1.279682,0.530549,1.810230,0.319920,0.132637,0.452558
12,scene_level2,0,4,1.566800,0.346692,1.913492,0.391700,0.086673,0.478373
15,scene_level2,4,4,1.816666,0.174850,1.991516,0.454166,0.043713,0.497879
19,scene_level2,9,4,1.625861,0.432055,2.057916,0.406465,0.108014,0.514479
18,scene_level2,7,4,1.957810,0.236422,2.194233,0.489453,0.059106,0.548558
21,scene_level3,0,4,0.970772,0.163692,1.134464,0.242693,0.040923,0.283616
22,scene_level3,1,4,0.923614,0.384514,1.308128,0.230904,0.096129,0.327032
20,scene_level3,baseline,22,0.778163,1.147721,1.925884,0.035371,0.052169,0.087540
27,scene_level3,6,4,1.914669,0.107231,2.021900,0.478667,0.026808,0.505475
26,scene_level3,5,18,1.826125,0.210314,2.036439,0.101451,0.011684,0.113135
23,scene_level3,2,25,1.828273,0.354151,2.182423,0.073131,0.014166,0.087297
30,scene_level3,9,8,1.530185,0.804563,2.334748,0.191273,0.100570,0.291843
29,scene_level3,8,4,2.142169,0.291622,2.433790,0.535542,0.072905,0.608448
25,scene_level3,4,7,2.007153,0.525458,2.532612,0.286736,0.075065,0.361802
28,scene_level3,7,30,2.178144,0.430666,2.608810,0.072605,0.014356,0.086960
24,scene_level3,3,4,2.358130,0.475567,2.833698,0.589533,0.118892,0.708424

In [17]:
df.sort_values(by=["scene", "avg_total_cost"], ascending=[True, True], inplace=True)
df

,scene,sample,traj_len,me_cost,safety_cost,total_cost,avg_me_cost,avg_safety_cost,avg_total_cost
7,scene,6,4,0.698019,0.115104,0.813123,0.174505,0.028776,0.203281
6,scene,5,4,0.690480,0.189030,0.879510,0.172620,0.047258,0.219877
3,scene,2,4,0.576708,0.304928,0.881636,0.144177,0.076232,0.220409
1,scene,0,4,0.749366,0.132311,0.881677,0.187342,0.033078,0.220419
2,scene,1,4,0.600664,0.362170,0.962834,0.150166,0.090542,0.240708
10,scene,9,4,0.684983,0.355419,1.040402,0.171246,0.088855,0.260100
8,scene,7,4,0.786060,0.373025,1.159085,0.196515,0.093256,0.289771
0,scene,baseline,2,0.527572,0.059571,0.587143,0.263786,0.029785,0.293571
5,scene,4,4,0.952456,0.222650,1.175106,0.238114,0.055662,0.293776
4,scene,3,4,0.989617,0.201499,1.191116,0.247404,0.050375,0.297779
9,scene,8,4,1.037262,0.301223,1.338485,0.259316,0.075306,0.334621
17,scene_level2,6,4,1.291845,0.201637,1.493482,0.322961,0.050409,0.373370
13,scene_level2,1,4,1.279678,0.429844,1.709522,0.319920,0.107461,0.427380
16,scene_level2,5,4,1.305953,0.484513,1.790466,0.326488,0.121128,0.447617
14,scene_level2,2,4,1.279682,0.530549,1.810230,0.319920,0.132637,0.452558
12,scene_level2,0,4,1.566800,0.346692,1.913492,0.391700,0.086673,0.478373
15,scene_level2,4,4,1.816666,0.174850,1.991516,0.454166,0.043713,0.497879
19,scene_level2,9,4,1.625861,0.432055,2.057916,0.406465,0.108014,0.514479
18,scene_level2,7,4,1.957810,0.236422,2.194233,0.489453,0.059106,0.548558
11,scene_level2,baseline,2,1.178598,0.081499,1.260097,0.589299,0.040750,0.630048
28,scene_level3,7,30,2.178144,0.430666,2.608810,0.072605,0.014356,0.086960
23,scene_level3,2,25,1.828273,0.354151,2.182423,0.073131,0.014166,0.087297
20,scene_level3,baseline,22,0.778163,1.147721,1.925884,0.035371,0.052169,0.087540
26,scene_level3,5,18,1.826125,0.210314,2.036439,0.101451,0.011684,0.113135
21,scene_level3,0,4,0.970772,0.163692,1.134464,0.242693,0.040923,0.283616
30,scene_level3,9,8,1.530185,0.804563,2.334748,0.191273,0.100570,0.291843
22,scene_level3,1,4,0.923614,0.384514,1.308128,0.230904,0.096129,0.327032
25,scene_level3,4,7,2.007153,0.525458,2.532612,0.286736,0.075065,0.361802
27,scene_level3,6,4,1.914669,0.107231,2.021900,0.478667,0.026808,0.505475
29,scene_level3,8,4,2.142169,0.291622,2.433790,0.535542,0.072905,0.608448
24,scene_level3,3,4,2.358130,0.475567,2.833698,0.589533,0.118892,0.708424

In [18]:
df.to_csv("traj_cost_data.csv", index=False)